development:
  dialect: mysql
  database: example
  user: root
  password: root
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://mysql:root@127.0.0.1:5432/example?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://mysql:root@127.0.0.1:5432/example?sslmode=disable"}}
